import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 12,
  },
  loadingWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
  },
  errorCard: {
    backgroundColor: '#FFF1F2',
    borderColor: '#FDA4AF',
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  errorTitle: {
    color: '#9F1239',
    fontSize: 16,
    fontWeight: '800',
  },
  errorText: {
    color: '#9F1239',
    fontSize: 13,
    lineHeight: 18,
  },
  diagramCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 20,
    borderWidth: 1,
    gap: 16,
    padding: 18,
    ...Platform.select({
      web: {
        boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
      },
    }),
  },
  diagramHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionKicker: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  domainTitle: {
    color: '#0F172A',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  typeBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#E0F2FE',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  typeBadgeText: {
    color: '#0369A1',
    fontSize: 12,
    fontWeight: '900',
  },
  diagramRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 12,
  },
  domainNode: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    padding: 14,
  },
  domainNodeLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  domainNodeValue: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  arrowWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
  },
  frontChipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  frontChip: {
    backgroundColor: '#FFFFFF',
    borderColor: '#BFDBFE',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  frontChipText: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '800',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 16,
    borderWidth: 1,
    flexGrow: 1,
    flexBasis: 260,
    gap: 8,
    minHeight: 110,
    padding: 16,
  },
  summaryLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  summaryStack: {
    gap: 4,
  },
  summaryValue: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '800',
  },
  summaryMeta: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 18,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#BFDBFE',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  actionButtonPressed: {
    opacity: 0.78,
  },
  actionButtonDisabled: {
    opacity: 0.45,
  },
  actionButtonText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
});
