import { StyleSheet } from 'react-native';
import globalStyles from '@controleonline/ui-layout/src/react/styles/global';

const css = (palette = {}) => {
  const styles = StyleSheet.create({
    Profile: {
      flex: 1,
      backgroundColor: palette.pageBackground,
    },
    scrollContent: {
      paddingBottom: 40,
    },
    headerContainer: {
      alignItems: 'center',
      paddingTop: 32,
      paddingBottom: 24,
      backgroundColor: palette.pageBackground,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: palette.cardBackground,
      borderWidth: 4,
      borderColor: palette.cardBackground,
      shadowColor: '#64748B',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 4,
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: palette.buttonBackground,
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: palette.buttonBorder,
    },
    userName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: palette.textPrimary,
      marginBottom: 0,
      textAlign: 'center',
      flex: 1,
    },
    userNameRow: {
      width: '100%',
      maxWidth: 320,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 2,
      paddingHorizontal: 8,
    },
    userNameInput: {
      flex: 1,
      fontSize: 24,
      fontWeight: 'bold',
      color: palette.textPrimary,
      textAlign: 'center',
      paddingVertical: 0,
      outlineStyle: 'none',
    },
    editNameButton: {
      marginLeft: 8,
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    userAliasRow: {
      width: '100%',
      maxWidth: 280,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
      paddingHorizontal: 8,
    },
    userAlias: {
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      color: palette.textSecondary,
      textAlign: 'center',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    userAliasInput: {
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      color: palette.textSecondary,
      textAlign: 'center',
      paddingVertical: 0,
      outlineStyle: 'none',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    editAliasButton: {
      marginLeft: 8,
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    userEmail: {
      fontSize: 14,
      color: palette.textSecondary,
      textAlign: 'center',
      maxWidth: 320,
      paddingHorizontal: 12,
    },
    contentContainer: {
      paddingHorizontal: 20,
    },
    sectionContainer: {
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.textPrimary,
    },
    addButton: {
      width: 34,
      height: 34,
      borderRadius: 8,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      borderColor: palette.buttonBackground,
    },
    cardItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.cardBackground,
      borderRadius: 12,
      padding: 12,
      marginBottom: 8,
      shadowColor: '#64748B',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    cardItemWithActions: {
      paddingRight: 4,
    },
    cardIcon: {
      marginRight: 12,
    },
    input: {
      flex: 1,
      fontSize: 15,
      color: palette.textPrimary,
      padding: 0,
      outlineStyle: 'none',
    },
    deleteAction: {
      width: 34,
      height: 34,
      borderRadius: 8,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      borderColor: palette.buttonBackground,
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.cardBackground,
      borderRadius: 16,
      padding: 16,
      shadowColor: '#64748B',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    menuIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    menuItemText: {
      flex: 1,
      fontSize: 16,
      fontWeight: '600',
      color: palette.textPrimary,
    },
    saveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      borderRadius: 12,
      paddingVertical: 14,
      marginBottom: 12,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 3,
    },
    saveButtonDisabled: {
      opacity: 0.65,
    },
    saveButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.buttonText,
    },
    profileActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.buttonBackground,
      borderRadius: 12,
      paddingVertical: 14,
      marginBottom: 12,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 3,
    },
    profileActionButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.buttonText,
    },
    emptyText: {
      color: palette.textSecondary,
      fontStyle: 'italic',
      fontSize: 14,
      marginLeft: 4,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    errorText: {
      fontSize: 16,
      color: palette.textDanger,
    },
    loadingSkeletonContainer: {
      alignItems: 'center',
      paddingTop: 32,
      paddingBottom: 24,
      backgroundColor: palette.pageBackground,
    },
    skeletonAvatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: '#E2E8F0',
      marginBottom: 16,
    },
    skeletonName: {
      width: 180,
      height: 22,
      borderRadius: 10,
      backgroundColor: '#E2E8F0',
      marginBottom: 8,
    },
    skeletonEmail: {
      width: 140,
      height: 14,
      borderRadius: 8,
      backgroundColor: '#E2E8F0',
    },
    skeletonSection: {
      marginBottom: 20,
      backgroundColor: palette.cardBackground,
      borderRadius: 12,
      padding: 14,
      shadowColor: '#64748B',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    skeletonSectionHeader: {
      width: 130,
      height: 18,
      borderRadius: 8,
      backgroundColor: '#E2E8F0',
      marginBottom: 12,
    },
    skeletonLine: {
      height: 44,
      borderRadius: 10,
      backgroundColor: '#E2E8F0',
      marginBottom: 10,
    },
  });

  return {styles, globalStyles: globalStyles()};
};

export default css;
